# Generated by Django 5.2.5 on 2025-08-16 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0004_remove_review_email_remove_review_name_review_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
